export const DATA_WELCOME = "APP/DATA_WELCOM",
  HARD_BOARD = "WELCOME/HARD_BOARD",
  EASY_BOARD = "WELCOME/EASY_BOARD",
  MIDDLE_BOARD = "WELCOME/MIDDLE_BOARD",
  FLIP_TRUE = "FLIP_TRUE",
  FLIP_FALSE = "FLIP_FALSE",
  LOAD_FROM_LOCAL = "LOAD_FROM_LOCAL",
  MATCHED = "MATCHED";
